//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Diagnostics;
using System.ServiceModel;
using System.ServiceModel.Channels;
using AdminInterface.Models.PrgData;

namespace ConsoleApplication11.ServiceReference2
{
	[GeneratedCode("System.ServiceModel", "3.0.0.0")]
	[ServiceContract(ConfigurationName = "ServiceReference2.IStatisticService")]
	public interface IStatisticService
	{
		[OperationContract(Action = "http://tempuri.org/IStatisticService/GetUpdateInfo",
			ReplyAction = "http://tempuri.org/IStatisticService/GetUpdateInfoResponse")]
		UpdatingClientStatus[] GetUpdateInfo();

		[OperationContract(Action = "http://tempuri.org/IStatisticService/GetUpdatingClientCount")]
		int GetUpdatingClientCount();
	}

	[GeneratedCode("System.ServiceModel", "3.0.0.0")]
	public interface IStatisticServiceChannel : IStatisticService, IClientChannel
	{
	}

	[DebuggerStepThrough]
	[GeneratedCode("System.ServiceModel", "3.0.0.0")]
	public class StatisticServiceClient : ClientBase<IStatisticService>, IStatisticService
	{
		public StatisticServiceClient()
		{
		}

		public StatisticServiceClient(string endpointConfigurationName) :
			base(endpointConfigurationName)
		{
		}

		public StatisticServiceClient(string endpointConfigurationName, string remoteAddress) :
			base(endpointConfigurationName, remoteAddress)
		{
		}

		public StatisticServiceClient(string endpointConfigurationName, EndpointAddress remoteAddress) :
			base(endpointConfigurationName, remoteAddress)
		{
		}

		public StatisticServiceClient(Binding binding, EndpointAddress remoteAddress) :
			base(binding, remoteAddress)
		{
		}

		public UpdatingClientStatus[] GetUpdateInfo()
		{
			return Channel.GetUpdateInfo();
		}

		public int GetUpdatingClientCount()
		{
			return Channel.GetUpdatingClientCount();
		}
	}
}
