//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1434
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminInterface.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"
          Добрый день.

          Во вложении данного письма находится регистрационна карта участника информационной системы ""АналитФАРМАЦИЯ"".

          С уважением, Аналитическая компания ""Инфорум"", г. Воронеж

          Москва +7 495 6628727
          С.-Петербург +7 812 3090521
          Воронеж +7 4732 606000
          Челябинск +7 351 7298143
        ")]
        public string RegistrationCardEmailBody {
            get {
                return ((string)(this["RegistrationCardEmailBody"]));
            }
        }
    }
}
