//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminInterface.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("U:\\wwwroot\\ios\\Results\\{0}.zip")]
        public string UserPreparedDataFormatString {
            get {
                return ((string)(this["UserPreparedDataFormatString"]));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("net.tcp://localhost:900/RemotePriceProcessorService")]
        public string WCFServiceUrl {
            get {
                return ((string)(this["WCFServiceUrl"]));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"Направляем Вам регистрационную карту Аптеки с учетными данными (имя и пароль) для работы в системе АналитФармация – в приложении.

Направляем Вам материалы для самостоятельной установки (переустановки) копии программы АналитФармация (если Вы хотите сделать это самостоятельно)
Последний релиз программы доступен по адресу www.analit.net в разделе""ПРОГРАММА""
Выберите файлы для загрузки. Вы получите саморазворачивающийся архив.
Запустите его на исполнение.  После распаковки на выбранном Вами диске появится папка AnalitF. Из нее запустите файл analitf.exe
Далее програма запросит вписать учетные данные (имя и пароль) - возьмите их из регистрационной карты для каждого из пользователей - в приложении.
Там же, во вкладке ""Соединение"", настройте соединение с Интернет, если Вы соединяетесь через модем по телефонной линии, то поставьте галочку
""Устанавливать удаленное соединение"" и чуть ниже выберите используемое соединение. Если работаете через Прокси-сервер, войдите в соответствующую вкладку и пропишите необходимые настройки.

Успехов в работе.  Пожалуйста, сохраните регистрационную карту

При необходимости, готовы перезвонить и дать все необходимые консультации")]
        public string RegistrationCardEmailBodyForDrugstore {
            get {
                return ((string)(this["RegistrationCardEmailBodyForDrugstore"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\r\nНаправляем Вам регистрационную карту Поставщика с учетными данными (имя и парол" +
            "ь) для доступа к управлению Вашей информацией в системе электронного заказа Анал" +
            "итФармация. Регистрационная карта - в приложении.\r\n\r\nДля доступа к интерфейсу уп" +
            "равления на www.analit.net войдите в раздел “Пользователям”, введите имя и парол" +
            "ь из рег.карты.\r\nПросим Вас заполнить контактную информацию в разделе ”Контактна" +
            "я информация” и систематически проверять актуальность внесённых Вами данных.\r\nВ " +
            "разделе \"Прайс-листы\" Вы можете просмотреть информацию об их обработке и настрой" +
            "ке.\r\nВ разделе \"Управление сопоставлением\" работать с сопоставлением позиций Ваш" +
            "его прайс-листа в системе.\r\nВ разделе ”Клиенты” необходимо указать контактный E-" +
            "mail для связи клиентов с Вами. При входе в соответствующий регион, Вы получаете" +
            " список клиентов-аптек, по которым можете посмотреть информацию по обновлению да" +
            "нных той или иной аптеки, выставить скидки-наценки, сумму минимального заказа, о" +
            "пределить и выбрать ценовую колонку. А также именно здесь вам необходимо прописы" +
            "вать ваши внутренние коды, присвоенные конкретным аптекам (если эти коды должны " +
            "прописываться в направляемую Вам заявку).\r\nВ разделе \"Доставка заказов\" Вы может" +
            "е выбрать способ доставки заказов и произвести соответствующие настройки. Так на" +
            "пример, при доставке заказов Вам по электронной почте, Вам необходимо прописать " +
            "E-mail для доставки заказов (\"Настройка E-mail адресов\") в каждом из регионов Ва" +
            "шей работы, здесь же Вы можете выбрать один из стандартных форматов файлов-заказ" +
            "ов или, связавшись с нами, заказать персональный формат.\r\nВ разделе ”Управление " +
            "заказами” Вам доступны заказы, сделанные аптеками в Ваш адрес, которые при необх" +
            "одимости вы можете отправить себе повторно.\r\n\r\nДля отправки клиентам накладных/о" +
            "тказов вы также можете воспользоваться нашим сервисом. Для этого необходимо проп" +
            "исать свой E-mail отправки  накладных/отказов в разделе \"Доставка накладных/отка" +
            "зов\", а адреса клиентов вы можете найти в разделе ”Клиенты” под каждым из фактич" +
            "еских адресов доставки.\r\nТакже предлагаем вашему вниманию универсальный сервис о" +
            "тправки сообщений произвольной формы, включая вложенные файлы как во все аптеки " +
            "региона, так и адресно: либо в конкретную аптеку, либо конкретному клиенту. Ваше" +
            " сообщения будет доставлено клиенту и показано в рамках программы АналитФармация" +
            ".\r\nДля того чтобы воспользоваться данным функционалом вам необходимо: в разделе " +
            "\"Контактная информация\" добавить Ваш адрес в блок \"Список E-mail, с которых разр" +
            "ешена отправка писем клиентам АналитФармация\". Затем нужно отправить обычное эле" +
            "ктронное письмо на соответсвующий E-mail: E-mail для отправки письма всем клиент" +
            "ам региона указан в разделе \"Клиенты\" на странице со списком регионов; E-mail дл" +
            "я отправки письма конкретному клиенту можно получить при клике на конкретного кл" +
            "иента на странице со списком клиентов; E-mail для отправки письма в конкретную а" +
            "птеку (делающую заказ по конкретному адресу-доставки) указан при клике на соотве" +
            "тствующий адрес соответствующего клиента на странице со списком клиентов.\r\n\r\nНад" +
            "еемся, что работа с остальными разделами (опциями) нашей системы не составит для" +
            " Вас труда.\r\nГотовы ответить на любые Ваши вопросы, как по работе в представленн" +
            "ом выше интерфейсе, так и по любым аспектам нашего IT-взаимодействия.\r\nВНИМАНИЕ!" +
            " Информацию, указанную в регистрационной карте, необходимо хранить, т.к. она явл" +
            "яется ключом доступа к интерфейсу управления настройками клиентов.\r\nПросьба подт" +
            "вердить получение.")]
        public string RegistrationCardEmailBodyForSupplier {
            get {
                return ((string)(this["RegistrationCardEmailBodyForSupplier"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:58379/ci/")]
        public string ClientInterfaceUrl {
            get {
                return ((string)(this["ClientInterfaceUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("net.tcp://localhost:901/RemoteOrderSenderService")]
        public string WCFOrderSenderServiceUrl {
            get {
                return ((string)(this["WCFOrderSenderServiceUrl"]));
            }
        }
    }
}
